// Generated by gencpp from file beginner_package/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_PACKAGE_MESSAGE_ADDTWOINTS_H
#define BEGINNER_PACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_package/AddTwoIntsRequest.h>
#include <beginner_package/AddTwoIntsResponse.h>


namespace beginner_package
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_package::AddTwoInts > {
  static const char* value()
  {
    return "670e8ca138898ad7e5338b42a76db5c8";
  }

  static const char* value(const ::beginner_package::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_package::AddTwoInts > {
  static const char* value()
  {
    return "beginner_package/AddTwoInts";
  }

  static const char* value(const ::beginner_package::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_package::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_package::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_package::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_package::AddTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_package::AddTwoInts > 
template<>
struct DataType< ::beginner_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_package::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_package::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_package::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_package::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_package::AddTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_package::AddTwoInts > 
template<>
struct DataType< ::beginner_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_package::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_PACKAGE_MESSAGE_ADDTWOINTS_H
