// Generated by gencpp from file mobile_robot/PlanForHorizonRequest.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_PLANFORHORIZONREQUEST_H
#define MOBILE_ROBOT_MESSAGE_PLANFORHORIZONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mobile_robot/PlanInstance.h>

namespace mobile_robot
{
template <class ContainerAllocator>
struct PlanForHorizonRequest_
{
  typedef PlanForHorizonRequest_<ContainerAllocator> Type;

  PlanForHorizonRequest_()
    : total_robots(0)
    , horizon_length(0)
    , plans()  {
    }
  PlanForHorizonRequest_(const ContainerAllocator& _alloc)
    : total_robots(0)
    , horizon_length(0)
    , plans(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _total_robots_type;
  _total_robots_type total_robots;

   typedef int16_t _horizon_length_type;
  _horizon_length_type horizon_length;

   typedef std::vector< ::mobile_robot::PlanInstance_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mobile_robot::PlanInstance_<ContainerAllocator> >::other >  _plans_type;
  _plans_type plans;




  typedef boost::shared_ptr< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlanForHorizonRequest_

typedef ::mobile_robot::PlanForHorizonRequest_<std::allocator<void> > PlanForHorizonRequest;

typedef boost::shared_ptr< ::mobile_robot::PlanForHorizonRequest > PlanForHorizonRequestPtr;
typedef boost::shared_ptr< ::mobile_robot::PlanForHorizonRequest const> PlanForHorizonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mobile_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mobile_robot': ['/home/pi/catkin_ws/src/mobile_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "110487f1256d199309e59bf3a67dfecb";
  }

  static const char* value(const ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x110487f1256d1993ULL;
  static const uint64_t static_value2 = 0x09e59bf3a67dfecbULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_robot/PlanForHorizonRequest";
  }

  static const char* value(const ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 total_robots\n\
int16 horizon_length\n\
PlanInstance[] plans\n\
\n\
================================================================================\n\
MSG: mobile_robot/PlanInstance\n\
int16 robot_id\n\
int16 horizon_step\n\
float32 x\n\
float32 y\n\
float32 theta\n\
\n\
";
  }

  static const char* value(const ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_robots);
      stream.next(m.horizon_length);
      stream.next(m.plans);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanForHorizonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_robot::PlanForHorizonRequest_<ContainerAllocator>& v)
  {
    s << indent << "total_robots: ";
    Printer<int16_t>::stream(s, indent + "  ", v.total_robots);
    s << indent << "horizon_length: ";
    Printer<int16_t>::stream(s, indent + "  ", v.horizon_length);
    s << indent << "plans[]" << std::endl;
    for (size_t i = 0; i < v.plans.size(); ++i)
    {
      s << indent << "  plans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mobile_robot::PlanInstance_<ContainerAllocator> >::stream(s, indent + "    ", v.plans[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_PLANFORHORIZONREQUEST_H
