// Generated by gencpp from file mobile_robot/ShareLocalInformation.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_SHARELOCALINFORMATION_H
#define MOBILE_ROBOT_MESSAGE_SHARELOCALINFORMATION_H

#include <ros/service_traits.h>


#include <mobile_robot/ShareLocalInformationRequest.h>
#include <mobile_robot/ShareLocalInformationResponse.h>


namespace mobile_robot
{

struct ShareLocalInformation
{

typedef ShareLocalInformationRequest Request;
typedef ShareLocalInformationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShareLocalInformation
} // namespace mobile_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mobile_robot::ShareLocalInformation > {
  static const char* value()
  {
    return "1ee98618110ac3e0511341f8c0d6d3a0";
  }

  static const char* value(const ::mobile_robot::ShareLocalInformation&) { return value(); }
};

template<>
struct DataType< ::mobile_robot::ShareLocalInformation > {
  static const char* value()
  {
    return "mobile_robot/ShareLocalInformation";
  }

  static const char* value(const ::mobile_robot::ShareLocalInformation&) { return value(); }
};


// service_traits::MD5Sum< ::mobile_robot::ShareLocalInformationRequest> should match 
// service_traits::MD5Sum< ::mobile_robot::ShareLocalInformation > 
template<>
struct MD5Sum< ::mobile_robot::ShareLocalInformationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mobile_robot::ShareLocalInformation >::value();
  }
  static const char* value(const ::mobile_robot::ShareLocalInformationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobile_robot::ShareLocalInformationRequest> should match 
// service_traits::DataType< ::mobile_robot::ShareLocalInformation > 
template<>
struct DataType< ::mobile_robot::ShareLocalInformationRequest>
{
  static const char* value()
  {
    return DataType< ::mobile_robot::ShareLocalInformation >::value();
  }
  static const char* value(const ::mobile_robot::ShareLocalInformationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mobile_robot::ShareLocalInformationResponse> should match 
// service_traits::MD5Sum< ::mobile_robot::ShareLocalInformation > 
template<>
struct MD5Sum< ::mobile_robot::ShareLocalInformationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mobile_robot::ShareLocalInformation >::value();
  }
  static const char* value(const ::mobile_robot::ShareLocalInformationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobile_robot::ShareLocalInformationResponse> should match 
// service_traits::DataType< ::mobile_robot::ShareLocalInformation > 
template<>
struct DataType< ::mobile_robot::ShareLocalInformationResponse>
{
  static const char* value()
  {
    return DataType< ::mobile_robot::ShareLocalInformation >::value();
  }
  static const char* value(const ::mobile_robot::ShareLocalInformationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_SHARELOCALINFORMATION_H
