// Generated by gencpp from file mobile_robot/ExecuteMotionPrimitiveRequest.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_EXECUTEMOTIONPRIMITIVEREQUEST_H
#define MOBILE_ROBOT_MESSAGE_EXECUTEMOTIONPRIMITIVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_robot
{
template <class ContainerAllocator>
struct ExecuteMotionPrimitiveRequest_
{
  typedef ExecuteMotionPrimitiveRequest_<ContainerAllocator> Type;

  ExecuteMotionPrimitiveRequest_()
    : x(0)
    , y(0)
    , n(0)  {
    }
  ExecuteMotionPrimitiveRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , n(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _n_type;
  _n_type n;




  typedef boost::shared_ptr< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteMotionPrimitiveRequest_

typedef ::mobile_robot::ExecuteMotionPrimitiveRequest_<std::allocator<void> > ExecuteMotionPrimitiveRequest;

typedef boost::shared_ptr< ::mobile_robot::ExecuteMotionPrimitiveRequest > ExecuteMotionPrimitiveRequestPtr;
typedef boost::shared_ptr< ::mobile_robot::ExecuteMotionPrimitiveRequest const> ExecuteMotionPrimitiveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mobile_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mobile_robot': ['/home/pi/catkin_ws/src/mobile_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f1cb68b714386a11b6223ca09a5405";
  }

  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f1cb68b714386aULL;
  static const uint64_t static_value2 = 0x11b6223ca09a5405ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_robot/ExecuteMotionPrimitiveRequest";
  }

  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
int64 n\n\
";
  }

  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.n);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteMotionPrimitiveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_robot::ExecuteMotionPrimitiveRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "n: ";
    Printer<int64_t>::stream(s, indent + "  ", v.n);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_EXECUTEMOTIONPRIMITIVEREQUEST_H
