// Generated by gencpp from file mobile_robot/ExecuteMotionPrimitive.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_EXECUTEMOTIONPRIMITIVE_H
#define MOBILE_ROBOT_MESSAGE_EXECUTEMOTIONPRIMITIVE_H

#include <ros/service_traits.h>


#include <mobile_robot/ExecuteMotionPrimitiveRequest.h>
#include <mobile_robot/ExecuteMotionPrimitiveResponse.h>


namespace mobile_robot
{

struct ExecuteMotionPrimitive
{

typedef ExecuteMotionPrimitiveRequest Request;
typedef ExecuteMotionPrimitiveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteMotionPrimitive
} // namespace mobile_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mobile_robot::ExecuteMotionPrimitive > {
  static const char* value()
  {
    return "68a20426c883aaf1dc5948a790ae4bc0";
  }

  static const char* value(const ::mobile_robot::ExecuteMotionPrimitive&) { return value(); }
};

template<>
struct DataType< ::mobile_robot::ExecuteMotionPrimitive > {
  static const char* value()
  {
    return "mobile_robot/ExecuteMotionPrimitive";
  }

  static const char* value(const ::mobile_robot::ExecuteMotionPrimitive&) { return value(); }
};


// service_traits::MD5Sum< ::mobile_robot::ExecuteMotionPrimitiveRequest> should match 
// service_traits::MD5Sum< ::mobile_robot::ExecuteMotionPrimitive > 
template<>
struct MD5Sum< ::mobile_robot::ExecuteMotionPrimitiveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mobile_robot::ExecuteMotionPrimitive >::value();
  }
  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobile_robot::ExecuteMotionPrimitiveRequest> should match 
// service_traits::DataType< ::mobile_robot::ExecuteMotionPrimitive > 
template<>
struct DataType< ::mobile_robot::ExecuteMotionPrimitiveRequest>
{
  static const char* value()
  {
    return DataType< ::mobile_robot::ExecuteMotionPrimitive >::value();
  }
  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mobile_robot::ExecuteMotionPrimitiveResponse> should match 
// service_traits::MD5Sum< ::mobile_robot::ExecuteMotionPrimitive > 
template<>
struct MD5Sum< ::mobile_robot::ExecuteMotionPrimitiveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mobile_robot::ExecuteMotionPrimitive >::value();
  }
  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mobile_robot::ExecuteMotionPrimitiveResponse> should match 
// service_traits::DataType< ::mobile_robot::ExecuteMotionPrimitive > 
template<>
struct DataType< ::mobile_robot::ExecuteMotionPrimitiveResponse>
{
  static const char* value()
  {
    return DataType< ::mobile_robot::ExecuteMotionPrimitive >::value();
  }
  static const char* value(const ::mobile_robot::ExecuteMotionPrimitiveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_EXECUTEMOTIONPRIMITIVE_H
