// Generated by gencpp from file mobile_robot/PlanInstance.msg
// DO NOT EDIT!


#ifndef MOBILE_ROBOT_MESSAGE_PLANINSTANCE_H
#define MOBILE_ROBOT_MESSAGE_PLANINSTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobile_robot
{
template <class ContainerAllocator>
struct PlanInstance_
{
  typedef PlanInstance_<ContainerAllocator> Type;

  PlanInstance_()
    : robot_id(0)
    , horizon_step(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  PlanInstance_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , horizon_step(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _robot_id_type;
  _robot_id_type robot_id;

   typedef int16_t _horizon_step_type;
  _horizon_step_type horizon_step;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::mobile_robot::PlanInstance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_robot::PlanInstance_<ContainerAllocator> const> ConstPtr;

}; // struct PlanInstance_

typedef ::mobile_robot::PlanInstance_<std::allocator<void> > PlanInstance;

typedef boost::shared_ptr< ::mobile_robot::PlanInstance > PlanInstancePtr;
typedef boost::shared_ptr< ::mobile_robot::PlanInstance const> PlanInstanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_robot::PlanInstance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_robot::PlanInstance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mobile_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mobile_robot': ['/home/pi/catkin_ws/src/mobile_robot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::PlanInstance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_robot::PlanInstance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::PlanInstance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_robot::PlanInstance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::PlanInstance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_robot::PlanInstance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_robot::PlanInstance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96ac8a4684b342746e9a5d5c6e606a85";
  }

  static const char* value(const ::mobile_robot::PlanInstance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96ac8a4684b34274ULL;
  static const uint64_t static_value2 = 0x6e9a5d5c6e606a85ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_robot::PlanInstance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_robot/PlanInstance";
  }

  static const char* value(const ::mobile_robot::PlanInstance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_robot::PlanInstance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 robot_id\n\
int16 horizon_step\n\
float32 x\n\
float32 y\n\
float32 theta\n\
\n\
";
  }

  static const char* value(const ::mobile_robot::PlanInstance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_robot::PlanInstance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.horizon_step);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanInstance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_robot::PlanInstance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_robot::PlanInstance_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "horizon_step: ";
    Printer<int16_t>::stream(s, indent + "  ", v.horizon_step);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_ROBOT_MESSAGE_PLANINSTANCE_H
