(cl:defpackage mobile_robot-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "EXECUTEMOTIONPRIMITIVE"
   "<EXECUTEMOTIONPRIMITIVE-REQUEST>"
   "EXECUTEMOTIONPRIMITIVE-REQUEST"
   "<EXECUTEMOTIONPRIMITIVE-RESPONSE>"
   "EXECUTEMOTIONPRIMITIVE-RESPONSE"
   "PLANFORHORIZON"
   "<PLANFORHORIZON-REQUEST>"
   "PLANFORHORIZON-REQUEST"
   "<PLANFORHORIZON-RESPONSE>"
   "PLANFORHORIZON-RESPONSE"
   "SHARELOCALINFORMATION"
   "<SHARELOCALINFORMATION-REQUEST>"
   "SHARELOCALINFORMATION-REQUEST"
   "<SHARELOCALINFORMATION-RESPONSE>"
   "SHARELOCALINFORMATION-RESPONSE"
  ))

