// Generated by gencpp from file beginner_package/CheckAddTwo.msg
// DO NOT EDIT!


#ifndef BEGINNER_PACKAGE_MESSAGE_CHECKADDTWO_H
#define BEGINNER_PACKAGE_MESSAGE_CHECKADDTWO_H

#include <ros/service_traits.h>


#include <beginner_package/CheckAddTwoRequest.h>
#include <beginner_package/CheckAddTwoResponse.h>


namespace beginner_package
{

struct CheckAddTwo
{

typedef CheckAddTwoRequest Request;
typedef CheckAddTwoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckAddTwo
} // namespace beginner_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_package::CheckAddTwo > {
  static const char* value()
  {
    return "670e8ca138898ad7e5338b42a76db5c8";
  }

  static const char* value(const ::beginner_package::CheckAddTwo&) { return value(); }
};

template<>
struct DataType< ::beginner_package::CheckAddTwo > {
  static const char* value()
  {
    return "beginner_package/CheckAddTwo";
  }

  static const char* value(const ::beginner_package::CheckAddTwo&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_package::CheckAddTwoRequest> should match 
// service_traits::MD5Sum< ::beginner_package::CheckAddTwo > 
template<>
struct MD5Sum< ::beginner_package::CheckAddTwoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_package::CheckAddTwo >::value();
  }
  static const char* value(const ::beginner_package::CheckAddTwoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_package::CheckAddTwoRequest> should match 
// service_traits::DataType< ::beginner_package::CheckAddTwo > 
template<>
struct DataType< ::beginner_package::CheckAddTwoRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_package::CheckAddTwo >::value();
  }
  static const char* value(const ::beginner_package::CheckAddTwoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_package::CheckAddTwoResponse> should match 
// service_traits::MD5Sum< ::beginner_package::CheckAddTwo > 
template<>
struct MD5Sum< ::beginner_package::CheckAddTwoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_package::CheckAddTwo >::value();
  }
  static const char* value(const ::beginner_package::CheckAddTwoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_package::CheckAddTwoResponse> should match 
// service_traits::DataType< ::beginner_package::CheckAddTwo > 
template<>
struct DataType< ::beginner_package::CheckAddTwoResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_package::CheckAddTwo >::value();
  }
  static const char* value(const ::beginner_package::CheckAddTwoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_PACKAGE_MESSAGE_CHECKADDTWO_H
